spring:
  config:
    import: "optional:configserver:https://stag-server.xquare.app/equus-config/"
  cloud:
    config:
      name: schedule
      profile: ${SCHEDULE_PROFILE}

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, busrefresh
      base-path: /
      path-mapping:
        health: /
