spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maxLifetime: 580000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
    open-in-view: false
    database: mysql
    
auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY:dGVzdA==}
    header: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}
